skip-check:
  - CKV_GIT_1
  - CKV_AWS_18
  - CKV_AWS_40
  - CKV_AWS_88
  # Ensure that CloudWatch Log Group is encrypted by KMS: https://docs.bridgecrew.io/docs/ensure-that-cloudwatch-log-group-is-encrypted-by-kms
  - CKV_AWS_158
