[book]
title = "Multitenant+Multicluster management using GitHub Action pipelines, Terraform and Rancher"
language = "en"
description = "Few notes about Multitenant+Multicluster management using GitHub Action pipelines, Terraform and Rancher"
authors = ["Petr Ruzicka"]

[output.html]
additional-css = ["theme/css/custom.css"]
edit-url-template = "https://github.com/ruzickap/k8s-tf-rancher/edit/main/docs/{path}"
git-repository-url = "https://github.com/ruzickap/k8s-tf-rancher"
site-url = "/k8s-tf-rancher/"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
